[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput --clear']

[start]
cmd = 'python -m gunicorn sistema_reservas_edificio.wsgi:application --bind 0.0.0.0:$PORT'