# Generated by Django 5.2.5 on 2025-08-28 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('sala', 'Sala'), ('directorio', 'Directorio'), ('terraza', 'Terraza'), ('estacionamiento', 'Estacionamiento')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_visitante', models.CharField(blank=True, max_length=100)),
                ('placa_visitante', models.CharField(blank=True, max_length=15)),
                ('empresa_visitante', models.CharField(blank=True, max_length=100)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espacio')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.oficina')),
            ],
        ),
    ]
