# Generated by Django 5.2.5 on 2025-08-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='es_estacionamiento_visita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacio',
            name='oficina_propietaria',
            field=models.ForeignKey(blank=True, help_text='Oficina dueña de este estacionamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionamientos_propios', to='reservas.oficina'),
        ),
    ]
