# Generated by Django 5.2.5 on 2025-08-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_espacio_es_estacionamiento_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='horarios_personalizados',
            field=models.JSONField(blank=True, default=list, help_text='Horarios específicos para este espacio'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='usar_horarios_personalizados',
            field=models.BooleanField(default=False, help_text='Usar horarios específicos en lugar de horarios estándar'),
        ),
    ]
