# Generated by Django 5.2.5 on 2025-09-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_espacio_horarios_personalizados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='tipo',
            field=models.CharField(choices=[('sala', 'Sala'), ('directorio', 'Directorio'), ('terraza', 'Terraza'), ('estacionamiento', 'Estacionamiento'), ('comedor', 'Comedor')], max_length=20),
        ),
    ]
